### ISSUE TITLE
GPU specifications for character-level PTB

### ISSUE THREAD

**Issue by arvieFrydenlund** [locuslab/trellisnet#2]
Hi, I'm wondering what GPU you used to train the character-level PTB model?  Just so I know how much vram the GPU needs to train given your hyper-parameters.   

Thanks

**Comment by shaojieb** [comment]
Hi! Thanks for your interest in our work. 

To train the model with default parameters you should need around 9GB available memory on each GPU. But if you load the pretrained weights, very few memory (around 1.5GB) should be sufficient. I used 1080-Ti.

Hope this helps :-)

**Comment by saikrishna-1996** [comment]
Hey, 
thanks for the great work and neat code!
My question is about training char_PTB. What do you mean by "Each GPU"? assuming that I am running on a single GPU, how much memory is required? I tried a max of 16GB with 1 GPU but I still got CUDA out of memory errors. (It worked however when I reduced the batch size to 4. but, I want to run with default batch size of 24))

**Comment by shaojieb** [comment]
Hi @saikrishna-1996 ! Sorry for the late reply (I didn't notice this reply in a closed issue...)

You need to use multiple GPUs in order to run a deep TrellisNet. For char-PTB, the default is 140 layers, which is hard to fit into one GPU. If a multiple-GPU setting is not directly available to you, then I suggest either batch-chunking or gradient checkpointing, which will greatly reduce the memory requirement of the network. If your GPU is 1080 or above, you could also use apex and half precision.

Hope this helps!
